// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/state.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/migueleliasweb/kubernetes-state-aggregation/pkg/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StateServiceName is the fully-qualified name of the StateService service.
	StateServiceName = "ksa.v1.StateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StateServiceFetchResourceGraphProcedure is the fully-qualified name of the StateService's
	// FetchResourceGraph RPC.
	StateServiceFetchResourceGraphProcedure = "/ksa.v1.StateService/FetchResourceGraph"
	// StateServiceGetResourceProcedure is the fully-qualified name of the StateService's GetResource
	// RPC.
	StateServiceGetResourceProcedure = "/ksa.v1.StateService/GetResource"
	// StateServiceListResourcesProcedure is the fully-qualified name of the StateService's
	// ListResources RPC.
	StateServiceListResourcesProcedure = "/ksa.v1.StateService/ListResources"
)

// StateServiceClient is a client for the ksa.v1.StateService service.
type StateServiceClient interface {
	FetchResourceGraph(context.Context, *connect.Request[v1.FetchResourceGraphRequest]) (*connect.Response[v1.FetchResourceGraphResponse], error)
	GetResource(context.Context, *connect.Request[v1.GetResourceRequest]) (*connect.Response[v1.GetResourceResponse], error)
	ListResources(context.Context, *connect.Request[v1.ListResourcesRequest]) (*connect.Response[v1.ListResourcesResponse], error)
}

// NewStateServiceClient constructs a client for the ksa.v1.StateService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	stateServiceMethods := v1.File_v1_state_proto.Services().ByName("StateService").Methods()
	return &stateServiceClient{
		fetchResourceGraph: connect.NewClient[v1.FetchResourceGraphRequest, v1.FetchResourceGraphResponse](
			httpClient,
			baseURL+StateServiceFetchResourceGraphProcedure,
			connect.WithSchema(stateServiceMethods.ByName("FetchResourceGraph")),
			connect.WithClientOptions(opts...),
		),
		getResource: connect.NewClient[v1.GetResourceRequest, v1.GetResourceResponse](
			httpClient,
			baseURL+StateServiceGetResourceProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetResource")),
			connect.WithClientOptions(opts...),
		),
		listResources: connect.NewClient[v1.ListResourcesRequest, v1.ListResourcesResponse](
			httpClient,
			baseURL+StateServiceListResourcesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListResources")),
			connect.WithClientOptions(opts...),
		),
	}
}

// stateServiceClient implements StateServiceClient.
type stateServiceClient struct {
	fetchResourceGraph *connect.Client[v1.FetchResourceGraphRequest, v1.FetchResourceGraphResponse]
	getResource        *connect.Client[v1.GetResourceRequest, v1.GetResourceResponse]
	listResources      *connect.Client[v1.ListResourcesRequest, v1.ListResourcesResponse]
}

// FetchResourceGraph calls ksa.v1.StateService.FetchResourceGraph.
func (c *stateServiceClient) FetchResourceGraph(ctx context.Context, req *connect.Request[v1.FetchResourceGraphRequest]) (*connect.Response[v1.FetchResourceGraphResponse], error) {
	return c.fetchResourceGraph.CallUnary(ctx, req)
}

// GetResource calls ksa.v1.StateService.GetResource.
func (c *stateServiceClient) GetResource(ctx context.Context, req *connect.Request[v1.GetResourceRequest]) (*connect.Response[v1.GetResourceResponse], error) {
	return c.getResource.CallUnary(ctx, req)
}

// ListResources calls ksa.v1.StateService.ListResources.
func (c *stateServiceClient) ListResources(ctx context.Context, req *connect.Request[v1.ListResourcesRequest]) (*connect.Response[v1.ListResourcesResponse], error) {
	return c.listResources.CallUnary(ctx, req)
}

// StateServiceHandler is an implementation of the ksa.v1.StateService service.
type StateServiceHandler interface {
	FetchResourceGraph(context.Context, *connect.Request[v1.FetchResourceGraphRequest]) (*connect.Response[v1.FetchResourceGraphResponse], error)
	GetResource(context.Context, *connect.Request[v1.GetResourceRequest]) (*connect.Response[v1.GetResourceResponse], error)
	ListResources(context.Context, *connect.Request[v1.ListResourcesRequest]) (*connect.Response[v1.ListResourcesResponse], error)
}

// NewStateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStateServiceHandler(svc StateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	stateServiceMethods := v1.File_v1_state_proto.Services().ByName("StateService").Methods()
	stateServiceFetchResourceGraphHandler := connect.NewUnaryHandler(
		StateServiceFetchResourceGraphProcedure,
		svc.FetchResourceGraph,
		connect.WithSchema(stateServiceMethods.ByName("FetchResourceGraph")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetResourceHandler := connect.NewUnaryHandler(
		StateServiceGetResourceProcedure,
		svc.GetResource,
		connect.WithSchema(stateServiceMethods.ByName("GetResource")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListResourcesHandler := connect.NewUnaryHandler(
		StateServiceListResourcesProcedure,
		svc.ListResources,
		connect.WithSchema(stateServiceMethods.ByName("ListResources")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ksa.v1.StateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StateServiceFetchResourceGraphProcedure:
			stateServiceFetchResourceGraphHandler.ServeHTTP(w, r)
		case StateServiceGetResourceProcedure:
			stateServiceGetResourceHandler.ServeHTTP(w, r)
		case StateServiceListResourcesProcedure:
			stateServiceListResourcesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStateServiceHandler struct{}

func (UnimplementedStateServiceHandler) FetchResourceGraph(context.Context, *connect.Request[v1.FetchResourceGraphRequest]) (*connect.Response[v1.FetchResourceGraphResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ksa.v1.StateService.FetchResourceGraph is not implemented"))
}

func (UnimplementedStateServiceHandler) GetResource(context.Context, *connect.Request[v1.GetResourceRequest]) (*connect.Response[v1.GetResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ksa.v1.StateService.GetResource is not implemented"))
}

func (UnimplementedStateServiceHandler) ListResources(context.Context, *connect.Request[v1.ListResourcesRequest]) (*connect.Response[v1.ListResourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ksa.v1.StateService.ListResources is not implemented"))
}
