// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: state.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceRecord represents a serialized Kubernetes resource state.
type ResourceRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ClusterName     string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	GroupName       string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Version         string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Kind            string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace       string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,8,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Manifest        []byte                 `protobuf:"bytes,9,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Labels          []byte                 `protobuf:"bytes,10,opt,name=labels,proto3" json:"labels,omitempty"`
	Annotations     []byte                 `protobuf:"bytes,11,opt,name=annotations,proto3" json:"annotations,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceRecord) Reset() {
	*x = ResourceRecord{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRecord) ProtoMessage() {}

func (x *ResourceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRecord.ProtoReflect.Descriptor instead.
func (*ResourceRecord) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRecord) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceRecord) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ResourceRecord) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ResourceRecord) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResourceRecord) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRecord) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *ResourceRecord) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *ResourceRecord) GetLabels() []byte {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ResourceRecord) GetAnnotations() []byte {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ResourceRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ResourceInfo defines the base information to identify a resource.
type ResourceInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterName     string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Group           string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Kind            string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace       string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Uid             string                 `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,8,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceInfo) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ResourceInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ResourceInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResourceInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceInfo) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

// FetchResourceGraphRequest requests the dependency graph for a root resource.
type FetchResourceGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *ResourceInfo          `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResourceGraphRequest) Reset() {
	*x = FetchResourceGraphRequest{}
	mi := &file_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResourceGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResourceGraphRequest) ProtoMessage() {}

func (x *FetchResourceGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResourceGraphRequest.ProtoReflect.Descriptor instead.
func (*FetchResourceGraphRequest) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

func (x *FetchResourceGraphRequest) GetRoot() *ResourceInfo {
	if x != nil {
		return x.Root
	}
	return nil
}

// FetchResourceGraphResponse returns the list of unique resources in the graph.
type FetchResourceGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ResourceRecord      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResourceGraphResponse) Reset() {
	*x = FetchResourceGraphResponse{}
	mi := &file_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResourceGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResourceGraphResponse) ProtoMessage() {}

func (x *FetchResourceGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResourceGraphResponse.ProtoReflect.Descriptor instead.
func (*FetchResourceGraphResponse) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{3}
}

func (x *FetchResourceGraphResponse) GetItems() []*ResourceRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\x06ksa.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x03\n" +
	"\x0eResourceRecord\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x12\x1d\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tR\tgroupName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12)\n" +
	"\x10resource_version\x18\b \x01(\tR\x0fresourceVersion\x12\x1a\n" +
	"\bmanifest\x18\t \x01(\fR\bmanifest\x12\x16\n" +
	"\x06labels\x18\n" +
	" \x01(\fR\x06labels\x12 \n" +
	"\vannotations\x18\v \x01(\fR\vannotations\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe4\x01\n" +
	"\fResourceInfo\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\a \x01(\tR\x03uid\x12)\n" +
	"\x10resource_version\x18\b \x01(\tR\x0fresourceVersion\"E\n" +
	"\x19FetchResourceGraphRequest\x12(\n" +
	"\x04root\x18\x01 \x01(\v2\x14.ksa.v1.ResourceInfoR\x04root\"J\n" +
	"\x1aFetchResourceGraphResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.ksa.v1.ResourceRecordR\x05items2k\n" +
	"\fStateService\x12[\n" +
	"\x12FetchResourceGraph\x12!.ksa.v1.FetchResourceGraphRequest\x1a\".ksa.v1.FetchResourceGraphResponseBFZDgithub.com/migueleliasweb/kubernetes-state-aggregation/pkg/api/v1;v1b\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_state_proto_goTypes = []any{
	(*ResourceRecord)(nil),             // 0: ksa.v1.ResourceRecord
	(*ResourceInfo)(nil),               // 1: ksa.v1.ResourceInfo
	(*FetchResourceGraphRequest)(nil),  // 2: ksa.v1.FetchResourceGraphRequest
	(*FetchResourceGraphResponse)(nil), // 3: ksa.v1.FetchResourceGraphResponse
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_state_proto_depIdxs = []int32{
	4, // 0: ksa.v1.ResourceRecord.updated_at:type_name -> google.protobuf.Timestamp
	1, // 1: ksa.v1.FetchResourceGraphRequest.root:type_name -> ksa.v1.ResourceInfo
	0, // 2: ksa.v1.FetchResourceGraphResponse.items:type_name -> ksa.v1.ResourceRecord
	2, // 3: ksa.v1.StateService.FetchResourceGraph:input_type -> ksa.v1.FetchResourceGraphRequest
	3, // 4: ksa.v1.StateService.FetchResourceGraph:output_type -> ksa.v1.FetchResourceGraphResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
